
# Code constants configuration file


birds_number: 50
alignment_const: 0.01
separation_limit: 100
cohesion_limit: 10000
cohesion_const: 0.125
horizontal_position_bounds: [-450.0, 50.0]
vertical_position_bounds: [300.0, 600.0]
horizontal_velocity_bounds: [0.0, 10.0]
vertical_velocity_bounds: [-20.0, 20.0]